In [3]:
import pandas as pd
df1 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/29/p1.csv', encoding='cp949')
df1.head(2).transpose()

               0        1
순번             1        1
계약구분          유효       유효
재계약횟수         10       10
거주개월         222      222
아파트 이름     강남아파트    강남아파트
아파트 ID         5        5
아파트 평점         7        7
호실고유번호     14520    14520
층              1        1
평형대           12       12
계약자고유번호    15468    15468
계약서고유번호    15865    15865
입주연도        2003     2003
퇴거연도         NaN      NaN
거주연도        2008     2009
월세(원)      47100    56500
보증금(원)   3646000  4375000
대표나이          46       46
나이            33       34
성별             남        남
결혼여부          미혼       미혼
거주자 수          3        3
퇴거여부         미퇴거      미퇴거

In [8]:
import pandas as pd
df1 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/29/p1.csv', encoding='cp949')


# 1. 정렬 수행 (필수)
df1 = df1.sort_values(by=['계약자고유번호', '거주연도'])

# 2. 그룹별 행 번호 할당
df1['rn'] = df1.groupby('계약자고유번호').cumcount() + 1

df1 = df1[df1['rn']==1]

df1.head(2)

,순번,계약구분,재계약횟수,거주개월,아파트 이름,아파트 ID,아파트 평점,호실고유번호,층,평형대,...,거주연도,월세(원),보증금(원),대표나이,나이,성별,결혼여부,거주자 수,퇴거여부,rn
85368,12673,해지,4,88,지산5단지아파트,3,8.0,85369,6,12,...,2008,52100,3575000,44,31,남,기혼,2,미퇴거,1
85420,12683,해지,7,174,지산5단지아파트,3,8.0,85421,6,15,...,2009,44900,2082000,32,20,남,미혼,1,미퇴거,1

In [21]:
import pandas_profiling

profile = df1.profile_report(title='temp', correlations = {'phi_k':False})

profile

In [20]:
df1['재계약횟수_bool'] = df1['재계약횟수'].apply(lambda x:'높음' if x>=df1['재계약횟수'].median() else '낮음')

df1.head(2)

,순번,계약구분,재계약횟수,거주개월,아파트 이름,아파트 ID,아파트 평점,호실고유번호,층,평형대,...,월세(원),보증금(원),대표나이,나이,성별,결혼여부,거주자 수,퇴거여부,rn,재계약횟수_bool
85368,12673,해지,4,88,지산5단지아파트,3,8.0,85369,6,12,...,52100,3575000,44,31,남,기혼,2,미퇴거,1,낮음
85420,12683,해지,7,174,지산5단지아파트,3,8.0,85421,6,15,...,44900,2082000,32,20,남,미혼,1,미퇴거,1,높음

In [ ]:
import statsmodels.api as sm
dir(sm)

In [26]:
import pandas as pd
df4 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/29/p2_.csv')
df4.head(2)
# df.describe()

# df.columns

,game_id,a1_1,a1_2,a2_1,a2_2,a3_1,a3_2,a4_1,a4_2,a5_1,...,a9_2,b1,b2,b3,b4,b5,b6,b7,b8,b9
0,201900016,5,5,5,5,5,5,5,5,5,...,5,0,0,0,0,0,0,0,4,2
1,201900023,6,4,5,5,2,5,1,1,6,...,7,3,0,0,1,0,1,3,1,0

In [31]:
df4.columns

Index(['game_id', 'a1_1', 'a1_2', 'a2_1', 'a2_2', 'a3_1', 'a3_2', 'a4_1',
       'a4_2', 'a5_1', 'a5_2', 'a6_1', 'a6_2', 'a7_1', 'a7_2', 'a8_1', 'a8_2',
       'a9_1', 'a9_2', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9'],
      dtype='object')

In [107]:
df4_long = df4

# df4_long = df4_long[]


# ['a1_1', 'a1_2', 'a2_1', 'a2_2', 'a3_1', 'a3_2', 'a4_1',
#        'a4_2', 'a5_1', 'a5_2', 'a6_1', 'a6_2', 'a7_1', 'a7_2', 'a8_1', 'a8_2',
#        'a9_1', 'a9_2', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9']

df4_long = df4_long.melt('game_id')

df4_long['batteridx'] = df4_long['variable'].str.split('_').str[1].fillna('-1').map({'-1':'3_score', '1': '1_first', '2': '2_second'})

df4_long['variable'] = df4_long['variable'].str.split('_').str[0]
df4_long = df4_long[df4_long['value'].isin([1,2,3,4,5,6,7,8,9])]


df4_long['round'] = df4_long['variable'].str.replace('a','').str.replace('b','')



df4_long = df4_long.pivot(index=['game_id', 'round'], columns=['batteridx'], values='value').reset_index()

df4_long.columns.name = None

df4_long = df4_long[(df4_long['1_first']!=4) & (df4_long['2_second']!=4)]

# df4_long.to_csv('temp.csv')

# help(df4_long.reset_index)

# df4_long[['batteridx']]

In [100]:
df4_long

        game_id round 1_first 2_second 3_score
0     201900016     1       5        5       0
1     201900016     2       5        5       0
2     201900016     3       5        5       0
3     201900016     4       5        5       0
4     201900016     5       5        5       0
...         ...   ...     ...      ...     ...
1794  201902394     4       7        5       0
1795  201902394     5       6        7       0
1796  201902394     6       2        9       4
1797  201902394     7       7        5       0
1798  201902394     8       5        6       0

[1663 rows x 5 columns]

In [101]:
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df4

       game_id a1_1  a1_2 a2_1  a2_2  ...  b5  b6 b7  b8  b9
0    201900016    5     5    5     5  ...   0   0  0   4   2
1    201900023    6     4    5     5  ...   0   1  3   1   0
2    201900103    5     6    5     5  ...   4   1  2   0   1
3    201900112    5     7    6     1  ...   0   0  1   0   0
4    201900131    5     1    2     5  ...   2   2  0   1   0
..         ...  ...   ...  ...   ...  ...  ..  .. ..  ..  ..
195  201902346    7     5    7     4  ...   0   0  0   0   1
196  201902365    2     5    1     1  ...   1   0  0   0   2
197  201902373          7    5     6  ...   0   1  0   0   0
198  201902392    6     5    5     1  ...   0   0  0   2   1
199  201902394    2     4    7     4  ...   0   4  0   0   1

[200 rows x 28 columns]

In [89]:
set(df4_long['round'])

{'1', '2', '3', '4', '5', '6', '7', '8', '9'}

In [110]:
df4_long.groupby('2_second').count()

          game_id  round  1_first  3_score
2_second
1             249    249      150      127
2              82     82       35       55
3              11     11        6       10
5             738    738      387      171
6             124    124       68       60
7             356    356      195       59
8              14     14        5        7
9              89     89       59       63