In [1]:
import pandas as pd
df3 =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/23/problem3_covid2.csv')
df3.head(2)

  location        date  new_cases
0  Austria  2021-01-01     2096.0
1  Austria  2021-01-02     1391.0

In [31]:
acf_matrix

,lag_1,lag_2,lag_3,lag_4,lag_5,lag_6,lag_7,lag_8,lag_9,lag_10,...,lag_41,lag_42,lag_43,lag_44,lag_45,lag_46,lag_47,lag_48,lag_49,lag_50
Austria,0.919603,0.851054,0.803218,0.763862,0.757490,0.772973,0.789918,0.752641,0.701409,0.659140,...,0.220197,0.236273,0.207555,0.173948,0.147141,0.123771,0.113010,0.115670,0.119881,0.096559
Bangladesh,0.965426,0.930580,0.903649,0.886103,0.874632,0.872235,0.874654,0.841760,0.806690,0.775153,...,-0.001348,-0.017721,-0.049929,-0.078360,-0.102451,-0.122010,-0.139556,-0.151417,-0.162918,-0.188173
Bhutan,0.404971,0.444965,0.494015,0.354268,0.402436,0.386444,0.480287,0.429297,0.373746,0.451500,...,0.152084,0.124221,0.077947,0.087246,0.135123,0.194757,0.099211,0.123792,0.084785,0.049940
Chile,0.937209,0.860792,0.818513,0.814239,0.844770,0.914714,0.956108,0.903748,0.821373,0.775372,...,0.496344,0.524026,0.474413,0.399977,0.362660,0.351389,0.372498,0.422232,0.449224,0.399461
Colombia,0.979553,0.959433,0.943796,0.933879,0.929708,0.928058,0.924081,0.909421,0.891353,0.873567,...,0.229049,0.216640,0.196433,0.172526,0.147572,0.126388,0.108273,0.093634,0.079745,0.061872
Costa Rica,0.187559,0.020331,0.174987,0.172191,0.014462,0.266074,0.778419,0.242283,0.013294,0.141233,...,0.115804,0.378464,0.050197,-0.167756,-0.041225,-0.075895,-0.175560,0.094736,0.319493,0.026634
Dominica,0.122646,0.119100,-0.002318,0.129099,0.096388,0.397651,0.295431,0.314563,0.104657,0.054382,...,0.087392,0.086202,0.099103,0.038514,0.073562,0.091131,0.139980,0.014870,0.069456,0.018534
Dominican Republic,0.781358,0.699239,0.709387,0.668271,0.701668,0.732759,0.754971,0.700097,0.626890,0.577637,...,-0.035693,-0.049349,-0.094246,-0.143397,-0.150428,-0.161216,-0.158448,-0.146346,-0.152795,-0.203310
Eswatini,0.820218,0.721628,0.677337,0.677258,0.691659,0.759552,0.782008,0.719604,0.632287,0.588135,...,-0.069179,-0.072140,-0.090535,-0.116372,-0.125848,-0.131569,-0.146936,-0.147523,-0.148142,-0.164213
Ethiopia,0.925311,0.873836,0.847740,0.832921,0.841424,0.863669,0.878608,0.842621,0.790769,0.755952,...,-0.026111,-0.039959,-0.081048,-0.133044,-0.156673,-0.171972,-0.178780,-0.184302,-0.195631,-0.221740
Faeroe Islands,0.686160,0.710250,0.584663,0.544609,0.496580,0.399466,0.315596,0.240107,0.209322,0.124491,...,0.016996,0.017864,0.020675,0.012701,0.006688,0.006310,0.017186,0.014334,0.008381,-0.002987
Ghana,0.186956,0.236323,0.305757,0.313819,0.347954,0.364162,0.256990,0.334409,0.276729,0.350418,...,-0.000160,0.006298,-0.111243,-0.040187,-0.072093,0.021426,-0.046723,-0.060622,-0.094040,-0.082105
Greece,0.700962,0.562997,0.594133,0.567467,0.516717,0.634022,0.816770,0.579742,0.444745,0.475747,...,0.021982,0.116613,-0.081964,-0.163351,-0.136484,-0.154391,-0.192991,-0.081727,0.016333,-0.166612
Haiti,0.092904,0.188725,0.117694,0.083646,0.222823,0.284550,0.267644,0.193212,0.246262,0.051035,...,0.007346,-0.019366,0.030205,-0.085107,-0.036135,-0.113041,-0.086451,-0.068333,-0.026984,0.011852
Kenya,0.822740,0.677024,0.622662,0.618367,0.655714,0.758697,0.828758,0.728132,0.593947,0.505114,...,-0.155783,-0.104458,-0.175778,-0.284501,-0.333237,-0.342966,-0.326279,-0.250754,-0.204749,-0.285055
Kosovo,0.386680,0.382350,0.406972,0.365760,0.562872,0.370953,0.423271,0.477516,0.353546,0.341984,...,-0.164914,-0.127041,-0.129954,-0.142124,-0.177615,-0.213584,-0.178714,-0.145197,-0.138436,-0.193240
Kyrgyzstan,0.963166,0.960068,0.950856,0.940587,0.931666,0.917160,0.907806,0.897621,0.877398,0.865036,...,0.136526,0.116142,0.096828,0.077032,0.059886,0.041605,0.020700,0.010270,-0.004455,-0.018602
Libya,0.523551,0.554628,0.547963,0.529030,0.497117,0.413358,0.818322,0.393001,0.457498,0.460443,...,-0.052601,0.189367,-0.056103,-0.019237,-0.027760,-0.066932,-0.096360,-0.129809,0.084596,-0.141278
Maldives,0.934121,0.926617,0.898967,0.859778,0.840780,0.828478,0.805673,0.782085,0.764492,0.717273,...,-0.082034,-0.090367,-0.095361,-0.102172,-0.107056,-0.110565,-0.113088,-0.116671,-0.117245,-0.121235
Mauritius,0.157004,0.068096,0.139972,0.282727,0.136118,0.130953,0.607923,0.311757,0.075091,0.182532,...,0.052043,0.162870,0.119212,0.034109,0.053304,0.026675,0.016967,0.085000,0.125651,0.042108
Moldova,0.885542,0.753002,0.667341,0.659750,0.728630,0.836960,0.905539,0.822594,0.695376,0.598930,...,0.178818,0.206364,0.149532,0.069357,0.002282,-0.017147,-0.000148,0.042469,0.067074,0.023745
Montenegro,0.940588,0.923850,0.912645,0.900863,0.892173,0.890760,0.915175,0.868573,0.842797,0.826218,...,0.297155,0.296853,0.256440,0.232281,0.212340,0.191232,0.171819,0.160598,0.157271,0.122018
Morocco,0.933105,0.870180,0.844334,0.834235,0.836794,0.871649,0.910384,0.844946,0.782912,0.748172,...,0.021224,0.025932,-0.013153,-0.046506,-0.061748,-0.074524,-0.087950,-0.084765,-0.079064,-0.109924
Myanmar,0.972216,0.973829,0.957790,0.955129,0.942077,0.936400,0.924970,0.909636,0.885764,0.870175,...,0.318708,0.306633,0.293165,0.276882,0.264559,0.250611,0.237875,0.225168,0.213049,0.199942
Namibia,0.648255,0.736635,0.665326,0.709807,0.785586,0.648878,0.702668,0.613314,0.692098,0.683595,...,-0.018438,-0.033020,-0.033379,-0.042696,-0.092617,-0.071902,-0.096248,-0.101600,-0.102675,-0.110303
Nicaragua,-0.081411,-0.081677,-0.081943,-0.082209,-0.034171,-0.082342,0.885838,-0.081459,-0.043207,-0.081991,...,-0.068646,0.554804,-0.063665,-0.036543,-0.064197,-0.064463,0.002060,-0.064597,0.497207,-0.059850
Nigeria,0.797529,0.792440,0.827974,0.795388,0.756610,0.794045,0.800378,0.764438,0.723204,0.721403,...,0.136738,0.115638,0.083730,0.072607,0.046063,0.055474,0.031152,0.014137,0.014057,-0.010069
North Macedonia,0.799086,0.678190,0.689977,0.681002,0.655342,0.759077,0.889777,0.714526,0.592068,0.585778,...,-0.064305,0.001948,-0.079482,-0.163377,-0.171664,-0.180166,-0.204008,-0.175337,-0.108013,-0.177241
Norway,0.821435,0.737018,0.698038,0.679191,0.679866,0.730709,0.757263,0.668495,0.556827,0.505715,...,-0.111528,-0.070661,-0.122529,-0.183335,-0.187732,-0.181238,-0.163870,-0.112833,-0.067071,-0.111740
Palau,-0.010638,0.039858,-0.010707,-0.010742,-0.010777,-0.010812,-0.010846,-0.010881,-0.010916,-0.010951,...,-0.008052,-0.008087,-0.008122,-0.008157,-0.008191,-0.008226,-0.008261,-0.004319,-0.004354,-0.004389
Poland,0.939671,0.848592,0.802139,0.794416,0.819599,0.886316,0.924582,0.869803,0.779965,0.727800,...,0.204438,0.218786,0.185824,0.134062,0.102933,0.089274,0.088525,0.109223,0.123921,0.097070
Portugal,0.944494,0.882105,0.854912,0.837923,0.835419,0.861000,0.871848,0.811876,0.734139,0.687481,...,-0.031009,-0.032438,-0.047664,-0.062883,-0.070517,-0.076146,-0.078749,-0.074699,-0.074796,-0.086853
Russia,0.979211,0.957977,0.938766,0.920349,0.902177,0.888362,0.872459,0.850575,0.829594,0.806535,...,0.248906,0.240324,0.228997,0.216679,0.204913,0.194449,0.186775,0.180739,0.174734,0.167078
Saint Pierre and Miquelon,-0.013769,0.100639,-0.013859,-0.013904,-0.013949,-0.013994,-0.014039,-0.014084,-0.014129,-0.014174,...,-0.007849,-0.007894,-0.007939,-0.007984,-0.008029,-0.008074,-0.008119,-0.008164,-0.008209,-0.008254
Slovenia,0.780149,0.557703,0.513476,0.485989,0.455829,0.604037,0.741952,0.593900,0.399924,0.359615,...,0.227975,0.318596,0.248794,0.140534,0.118545,0.100315,0.079667,0.158651,0.239708,0.172274
Solomon Islands,-0.009966,-0.009999,-0.010031,-0.010064,-0.010097,-0.010129,-0.010162,-0.010194,-0.010227,-0.010259,...,-0.007958,-0.007990,-0.008023,-0.008056,-0.008088,-0.008121,-0.008153,-0.008186,0.328426,-0.008251
Tunisia,0.707691,0.708418,0.692422,0.670506,0.642907,0.642802,0.685664,0.594952,0.550495,0.535160,...,0.040154,-0.001583,-0.005436,0.003902,-0.018774,-0.022477,-0.044563,-0.033992,-0.029305,-0.016101
Uruguay,0.893337,0.878473,0.857043,0.852344,0.859448,0.877445,0.873509,0.848662,0.814941,0.802635,...,0.363550,0.349213,0.318196,0.307446,0.277603,0.269879,0.268444,0.268067,0.234721,0.243998
Vanuatu,-0.009221,-0.009251,-0.009282,-0.009312,-0.009342,-0.005696,-0.005726,-0.005756,-0.005786,-0.005816,...,-0.006750,-0.006780,-0.006811,0.217424,-0.006871,-0.006901,-0.006931,-0.006961,-0.006991,-0.007021

In [ ]:
df3_solve = df3

df3_solve = df3_solve.sort_values(['location', 'date'])

# df3_solve


df3_solve['cum_cases'] = df3_solve.groupby(['location'])['new_cases'].cumsum()


from statsmodels.tsa.stattools import acf
from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import linkage, dendrogram

df_wide = df3_solve.pivot(index='date', columns='location', values='new_cases').fillna(0)
# df_wide = df3_solve.pivot(index='date', columns='location', values='cum_cases').fillna(0)

df_wide

# 추천 방식: 리스트에 담아 한 번에 생성
acf_data = []
countries = []

for country in df_wide.columns:
    series = df_wide[country].dropna()
    if len(series) > 50:
        acfs = acf(series, nlags=50)[1:]
        acf_data.append(acfs)
        countries.append(country)

# 리스트를 데이터프레임으로 변환 (컬럼명을 Lag 1~50으로 자동 지정)
acf_matrix = pd.DataFrame(acf_data, index=countries, columns=[f'lag_{i}' for i in range(1, 51)])

dist_matrix = pdist(acf_matrix, metric='euclidean')
linkage_matrix = linkage(dist_matrix, method='ward')


# acf_matrix