In [3]:
import pandas as pd 
df1 = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/31/adp_31_1_obesity_v2.csv",index_col=0)
df1.head(2)

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,BMI
0,4,male,27,1.80,87,no,no,always,3,sometimes,no,between 1 and 2 l,no,2 to 4,0 to 2,frequently,walking,overweight_level_i,26.851852
1,11,male,26,1.85,105,yes,yes,always,3,frequently,no,more than 2 l,no,2 to 4,>5,sometimes,public_transportation,obesity_type_i,30.679328

In [10]:
df1_solve = df1

import pandas_profiling

profile = df1_solve.profile_report(title='temp', correlations = {'phi_k':False})

In [13]:
df1_solve.to_csv('temp2.csv')

In [14]:
df4 =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/31/adp_31_2_v2.csv')
df4.head()

,ID,키,weight,생년월일,건강검진일,공학여부,채소섭취정도,아침식사여부,일주일운동시간,수면시간,성별
0,ID_4135,169.01,65.47,20041003,2020_11_15,1,2,1,4.4,8.3,남성
1,ID_3289,181.62,69.36,19970725,2014_11_20,0,3,0,4.4,6.9,남성
2,ID_1847,160.89,65.12,20020921,2020_01_28,1,1,1,1.7,9.6,여성
3,ID_4785,162.21,62.28,20020106,2018_09_27,1,4,0,5.1,6.8,남성
4,ID_5693,159.13,54.11,19980708,2015_03_03,0,4,1,0.3,8.5,여성

0        True
1       False
2       False
3       False
4       False
        ...
6796    False
6797    False
6798    False
6799    False
6800     True
Length: 6801, dtype: bool

In [45]:
df4_solve = df4

df4_solve['bmi'] = df4_solve['weight']/((df4_solve['키']/100)**2)

# df4_solve['생년월일'].to_timestamp()

df4_solve['생년월일'] = pd.to_datetime(df4_solve['생년월일'], format='%Y%m%d')
df4_solve['건강검진일'] = pd.to_datetime(df4_solve['건강검진일'], format='%Y_%m_%d')

df4_solve['age'] = (df4_solve['건강검진일'] - df4_solve['생년월일']).dt.days//365

df4_solve['is_proper'] = (
((df4_solve['성별']=='남성') & (df4_solve['age']==17) & (df4_solve['bmi']>=21.03) & (df4_solve['bmi']<23.21))
|((df4_solve['성별']=='여성') & (df4_solve['age']==17) & (df4_solve['bmi']>=20.03) & (df4_solve['bmi']<22.39))
|((df4_solve['성별']=='남성') & (df4_solve['age']==16) & (df4_solve['bmi']>=21.18) & (df4_solve['bmi']<23.45))
|((df4_solve['성별']=='여성') & (df4_solve['age']==17) & (df4_solve['bmi']>=19.61) & (df4_solve['bmi']<21.74))
)


df4_solve

,ID,키,weight,생년월일,건강검진일,공학여부,채소섭취정도,아침식사여부,일주일운동시간,수면시간,성별,bmi,datediff,age,is_proper
0,ID_4135,169.01,65.47,2004-10-03,2020-11-15,1,2,1,4.4,8.3,남성,22.920154,16,16,True
1,ID_3289,181.62,69.36,1997-07-25,2014-11-20,0,3,0,4.4,6.9,남성,21.027214,17,17,False
2,ID_1847,160.89,65.12,2002-09-21,2020-01-28,1,1,1,1.7,9.6,여성,25.156852,17,17,False
3,ID_4785,162.21,62.28,2002-01-06,2018-09-27,1,4,0,5.1,6.8,남성,23.669733,16,16,False
4,ID_5693,159.13,54.11,1998-07-08,2015-03-03,0,4,1,0.3,8.5,여성,21.368469,16,16,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6796,ID_6443,156.04,55.36,2003-04-29,2020-04-23,1,4,1,7.8,9.3,여성,22.736531,16,16,False
6797,ID_3606,182.46,67.55,2005-05-28,2022-08-03,1,4,0,2.9,8.9,남성,20.290372,17,17,False
6798,ID_5704,150.18,48.29,2003-04-20,2020-02-29,0,1,1,6.0,7.8,여성,21.410805,16,16,False
6799,ID_6637,159.45,60.53,2000-07-18,2016-12-11,0,1,1,7.6,5.4,여성,23.807929,16,16,False
6800,ID_2575,171.23,67.05,2001-06-04,2019-02-01,1,0,0,8.0,9.0,남성,22.868573,17,17,True

In [48]:
import pandas as pd
df6 =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/31/adp_31_5_advertising.csv',index_col = 0)
df6.head(2)

df6_solve = df6

df6_solve = df6_solve.reset_index()

# import statsmodels.

In [75]:
import pandas as pd
df7 =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/31/adp_31_7.csv',index_col = 0)
df7_solve = df7

df7_solve = df7_solve.reset_index()

df7_solve



(pd.melt(df7_solve, id_vars='index').groupby('variable').sum('value')/12).reset_index()


# df7_solve

# help(pd.melt)

  variable     value
0        A  0.583333
1        B  0.666667
2        C  0.333333
3        D  0.583333
4        E  0.333333