In [1]:
import pandas as pd

df4 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/30/p2_v2.csv')
df4.head()

,사고년도,가해자성별,가해자연령,가해차종,가해자신체상해정도,피해자성별,피해자연령,피해차종,피해자신체상해정도,사고유형,가해자법규위반,기상상태,시각,사건번호
0,2015,남,46세,승합차,상해없음,여,64세,자전거,경상,차대차 - 기타,안전운전불이행,맑음,2015-07-03_10시,ID_796
1,2019,남,53세,승용차,상해없음,여,57세,자전거,경상,차대차 - 후진중충돌,안전운전불이행,맑음,2019-10-12_10시,ID_6697
2,2015,남,39세,승용차,상해없음,남,63세,자전거,중상,차대차 - 기타,기타,맑음,2015-03-23_20시,ID_919
3,2016,남,12세,자전거,상해없음,남,52세,보행자,경상,차대사람 - 길가장자리구역통행중,안전운전불이행,맑음,2016-04-10_15시,ID_2512
4,2015,남,54세,승용차,상해없음,남,63세,자전거,중상,차대차 - 기타,안전운전불이행,맑음,2015-08-04_6시,ID_75

In [29]:
df4_solve = df4



df4_solve['timestamp'] = pd.to_datetime(df4_solve['시각'], format='%Y-%m-%d_%H시')
# df4_solve['timestamp'] = pd.to_datetime(df4_solve['시각'], format='%Y-%M-%d_%H시')


df4_solve['is_weekend'] = df4_solve['timestamp'].dt.weekday.apply(lambda x: ((x==5)|(x==6)))

df4_solve

,사고년도,가해자성별,가해자연령,가해차종,가해자신체상해정도,피해자성별,피해자연령,피해차종,피해자신체상해정도,사고유형,가해자법규위반,기상상태,시각,사건번호,timestamp,is_weekend
0,2015,남,46세,승합차,상해없음,여,64세,자전거,경상,차대차 - 기타,안전운전불이행,맑음,2015-07-03_10시,ID_796,2015-07-03 10:00:00,False
1,2019,남,53세,승용차,상해없음,여,57세,자전거,경상,차대차 - 후진중충돌,안전운전불이행,맑음,2019-10-12_10시,ID_6697,2019-10-12 10:00:00,True
2,2015,남,39세,승용차,상해없음,남,63세,자전거,중상,차대차 - 기타,기타,맑음,2015-03-23_20시,ID_919,2015-03-23 20:00:00,False
3,2016,남,12세,자전거,상해없음,남,52세,보행자,경상,차대사람 - 길가장자리구역통행중,안전운전불이행,맑음,2016-04-10_15시,ID_2512,2016-04-10 15:00:00,True
4,2015,남,54세,승용차,상해없음,남,63세,자전거,중상,차대차 - 기타,안전운전불이행,맑음,2015-08-04_6시,ID_75,2015-08-04 06:00:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7821,2017,여,60세,승용차,상해없음,남,13세,자전거,경상,차대차 - 추돌,신호위반,맑음,2017-06-14_16시,ID_4444,2017-06-14 16:00:00,False
7822,2018,여,62세,승용차,상해없음,여,76세,자전거,중상,차대차 - 측면충돌,기타,맑음,2018-11-28_13시,ID_5736,2018-11-28 13:00:00,False
7823,2020,남,44세,승용차,상해없음,여,76세,자전거,경상,차대차 - 측면충돌,기타,맑음,2020-10-30_13시,ID_7537,2020-10-30 13:00:00,False
7824,2016,남,61세,승용차,상해없음,남,27세,자전거,경상,차대차 - 기타,기타,맑음,2016-08-05_22시,ID_2236,2016-08-05 22:00:00,False
7825,2015,남,73세,승합차,상해없음,남,76세,자전거,경상,차대차 - 측면직각충돌,기타,맑음,2015-04-11_10시,ID_1877,2015-04-11 10:00:00,True

In [31]:
import pandas as pd

# 데이터 정의
data = {
    '지역1': ['20만원', '15만원', '3만원'],
    '지역2': ['5만원', '2만원', '14만원'],
    '지역3': ['35만원', '20만원', '17만원'],
    '총 생산량': [75, 55, 60]
}

# 인덱스 설정
index = ['공장A', '공장B', '공장C']

# DataFrame 생성
df = pd.DataFrame(data, index=index)

# 하단 '총 수요량' 행 추가
df.loc['총 수요량'] = ['80', '50', '60', None]

df

        지역1   지역2   지역3 총 생산량
공장A    20만원   5만원  35만원    75
공장B    15만원   2만원  20만원    55
공장C     3만원  14만원  17만원    60
총 수요량    80    50    60  None

In [42]:
import pandas as pd

df6 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/30/p6.csv')
# df6.head(2)


pd.crosstab(df6['나이'], df6['선호도'])

import scipy.stats as stats


stats.chi2_contingency(pd.crosstab(df6['나이'], df6['선호도']))

# help(stats.chi2_contingency)[1]

(0.26510760957453305,
 0.9919538273457956,
 4,
 array([[35.53790614, 32.88086643, 23.58122744],
        [25.10830325, 23.23104693, 16.66064982],
        [46.35379061, 42.88808664, 30.75812274]]))